import logging

logger = logging.getLogger('app2')
logger.critical("faced error in functions module")
